# Web Scraping — KaBuM!

## Objetivo

Extrair **nome** e **preço** dos produtos de **Memória RAM** do site KaBuM.

## Imports

In [1]:
# %pip install requests
# %pip install bs4

import requests
from bs4 import BeautifulSoup
import json
import time
import random
import pathlib
import re
import pandas as pd

## Configurações

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept-Language": "pt-BR,pt;q=0.9",
}

## Procurando Padrões

Procure na ultima linha: <script id="__NEXT_DATA__"... dentro desta div, temos a type="application/json", o ouro esta aqui

In [3]:
url = "https://www.kabum.com.br/hardware/memoria-ram"

response = requests.get(url, headers=headers)
print("Status:", response.status_code)

Status: 200

In [4]:
soup = BeautifulSoup(response.text, "html.parser")
soup

<!DOCTYPE html>
<html lang="pt-br"><head><link as="style" fetchpriority="high" href="https://static.kabum.com.br/conteudo/temas/001/header2.0/banner_monte_seu_pc.png" rel="preload"/><meta charset="utf-8"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/><link href="https://images.kabum.com.br" rel="preconnect"/><link href="https://static.kabum.com.br" rel="preconnect"/><link href="https://themes.kabum.com.br" rel="preconnect"/><title>Memória RAM DDR5, DDR4 para PC e notebook</title><meta content="Memória RAM em promoção no KaBuM!
" name="title"/><meta content="Memórias RAM 8GB, 16GB e 32GB com descontos imperdíveis. Acelere seu PC ou notebook com performance confiável" name="description"/><link href="https://www.kabum.com.br/hardware/memoria-ram" rel="canonical"/><meta content="https://www.kabum.com.br/hardware/memoria-ram" property="og:url"/><meta content="website" property="og:type"/><meta content="Memória RAM em promoção no KaBuM!
" property="og:title"/><meta content="Memórias RAM 8GB, 16GB e 32GB com descontos imperdíveis. Acelere seu PC ou notebook com performance confiável" property="og:description"/><meta content="https://themes.kabum.com.br/conteudo/layout/7708/1775561320.jpg" property="og:image"/><meta content="@kabumcombr" name="twitter:site"/><meta content="summary_large_image" name="twitter:card"/><meta content="www.kabum.com.br" property="twitter:domain"/><meta content="https://www.kabum.com.br/hardware/memoria-ram" property="twitter:url"/><meta content="Memória RAM em promoção no KaBuM!
" name="twitter:title"/><meta content="Memórias RAM 8GB, 16GB e 32GB com descontos imperdíveis. Acelere seu PC ou notebook com performance confiável" name="twitter:description"/><meta content="https://themes.kabum.com.br/conteudo/layout/7708/1775561320.jpg" name="twitter:image"/><script type="application/ld+json">{
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "name": "Memória RAM em promoção no KaBuM!\r",
  "url": "https://www.kabum.com.br/hardware/memoria-ram",
  "description": "Memórias RAM 8GB, 16GB e 32GB com descontos imperdíveis. Acelere seu PC ou notebook com performance confiável",
  "breadcrumb": {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Início",
        "item": "https://www.kabum.com.br"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Hardware"
      },
      {
        "@type": "ListItem",
        "position": 3,
        "name": "Memória RAM"
      }
    ]
  },
  "mainEntity": {
    "@type": "ItemList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Hardware",
        "item": "https://www.kabum.com.br/hardware"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Memória RAM",
        "item": "https://www.kabum.com.br/memoria-ram"
      }
    ]
  }
}</script><meta content="24" name="next-head-count"/><script>
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl+'';
              f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-W3L5TR8');
            </script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-2140951-1"></script><script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', 'UA-2140951-1', {
                  page_path: window.location.pathname,
                });
              </script><link href="https://dev.visualwebsiteoptimizer.com" rel="preconnect"/><link href="https://themes.kabum.com.br" rel="preconnect"/><link href="https://themes.kabum.com.br" rel="dns-prefetch"/><link href="https://static.kabum.com.br" rel="preconnect"/><link href="https://static.kabum.com.br" rel="dns-prefetch"/><link href="https://static.kabum.com.br/conteudo/favicon/favicon.ico" rel="shortcut icon"/><meta charset="utf-8"/><meta content="text/html" http-equiv="Content-Type"/><meta content="pt-br" name="language"/><meta content="document" name="resource-type"/><meta content="1" name="revisit-after"/><meta content="Global" name="distribution"/><meta content="General" name="rating"/><meta content="KaBuM! | Maior E-commerce de Tecnologia e Games da América Latina" name="author"/><meta content="kabum, kabum loja, loja online, kabum referencias, kabum opinioes, kabum alguem ja comprou, kabum é boa, kabum seguro, kabum é confiavel, kabum.com.br, www.kabum.com.br, informatica, loja on-line, hardware" name="keywords"/><meta content="7869C68B5FA3025DA1BC53D472E4E66F" name="msvalidate.01"/><meta content="#0060b1ff" name="theme-color"/><meta content="#0060b1ff" name="apple-mobile-web-app-status-bar-style"/><link as="font" crossorigin="anonymous" data-next-font="size-adjust" href="/core/_next/static/media/eafabf029ad39a43-s.p.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="anonymous" data-next-font="size-adjust" href="/core/_next/static/media/8888a3826f4a3af4-s.p.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="anonymous" data-next-font="size-adjust" href="/core/_next/static/media/0484562807a97172-s.p.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="anonymous" data-next-font="size-adjust" href="/core/_next/static/media/b957ea75a84b6ea7-s.p.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="anonymous" data-next-font="size-adjust" href="/core/_next/static/media/7db6c35d839a711c-s.p.woff2" rel="preload" type="font/woff2"/><script data-nscript="beforeInteractive" id="vwoCode">window._vwo_code || (function() {
              var account_id=833870,
              version=2.0,
              settings_tolerance=2000,
              hide_element='body',
              hide_element_style = 'opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important',
              /* DO NOT EDIT BELOW THIS LINE */
              f=false,w=window,d=document,v=d.querySelector('#vwoCode'),cK='_vwo_'+account_id+'_settings',cc={};try{var c=JSON.parse(localStorage.getItem('_vwo_'+account_id+'_config'));cc=c&&typeof c==='object'?c:{}}catch(e){}var stT=cc.stT==='session'?w.sessionStorage:w.localStorage;code={use_existing_jquery:function(){return typeof use_existing_jquery!=='undefined'?use_existing_jquery:undefined},library_tolerance:function(){return typeof library_tolerance!=='undefined'?library_tolerance:undefined},settings_tolerance:function(){return cc.sT||settings_tolerance},hide_element_style:function(){return'{'+(cc.hES||hide_element_style)+'}'},hide_element:function(){return typeof cc.hE==='string'?cc.hE:hide_element},getVersion:function(){return version},finish:function(){if(!f){f=true;var e=d.getElementById('_vis_opt_path_hides');if(e)e.parentNode.removeChild(e)}},finished:function(){return f},load:function(e){var t=this.getSettings(),n=d.createElement('script'),i=this;if(t){n.textContent=t;d.getElementsByTagName('head')[0].appendChild(n);if(!w.VWO||VWO.caE){stT.removeItem(cK);i.load(e)}}else{n.fetchPriority='high';n.src=e;n.type='text/javascript';n.onerror=function(){_vwo_code.finish()};d.getElementsByTagName('head')[0].appendChild(n)}},getSettings:function(){try{var e=stT.getItem(cK);if(!e){return}e=JSON.parse(e);if(Date.now()>e.e){stT.removeItem(cK);return}return e.s}catch(e){return}},init:function(){if(d.URL.indexOf('__vwo_disable__')>-1)return;var e=this.settings_tolerance();w._vwo_settings_timer=setTimeout(function(){_vwo_code.finish();stT.removeItem(cK)},e);var t=d.currentScript,n=d.createElement('style'),i=this.hide_element(),r=t&&!t.async&&i?i+this.hide_element_style():'',c=d.getElementsByTagName('head')[0];n.setAttribute('id','_vis_opt_path_hides');v&&n.setAttribute('nonce',v.nonce);n.setAttribute('type','text/css');if(n.styleSheet)n.styleSheet.cssText=r;else n.appendChild(d.createTextNode(r));c.appendChild(n);this.load('https://dev.visualwebsiteoptimizer.com/j.php?a='+account_id+'&u='+encodeURIComponent(d.URL)+'&vn='+version)}};w._vwo_code=code;code.init();})();</script><link as="style" href="/core/_next/static/css/7a90f5ad57bf441a.css" rel="preload"/><link data-n-g="" href="/core/_next/static/css/7a90f5ad57bf441a.css" rel="stylesheet"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/core/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><script data-nscript="beforeInteractive" defer="" id="insider-init" src="/scripts/insider-init.js" type="application/javascript"></script><script defer="" src="/core/_next/static/chunks/webpack-c739cf2b61fa7d76.js"></script><script defer="" src="/core/_next/static/chunks/framework-170ad79b54905cef.js"></script><script defer="" src="/core/_next/static/chunks/main-1b6a398cea2f0fa2.js"></script><script defer="" src="/core/_next/static/chunks/pages/_app-b97d6e92d286788c.js"></script><script defer="" src="/core/_next/static/chunks/4968-3d2537edcf995ae4.js"></script><script defer="" src="/core/_next/static/chunks/9332-4bfc11df2a7dc50c.js"></script><script defer="" src="/core/_next/static/chunks/4827-39653a579573fe32.js"></script><script defer="" src="/core/_next/static/chunks/3264-b1e3343eaee5455a.js"></script><script defer="" src="/core/_next/static/chunks/5249-c58e1d1e4f29a356.js"></script><script defer="" src="/core/_next/static/chunks/7316-35ce8455daafd4e8.js"></script><script defer="" src="/core/_next/static/chunks/4109-22e01c6ad5d34ffb.js"></script><script defer="" src="/core/_next/static/chunks/4099-16a24ee3dce73b42.js"></script><script defer="" src="/core/_next/static/chunks/2485-235a63992ff7b719.js"></script><script defer="" src="/core/_next/static/chunks/pages/%5B...categoria%5D-29e4ca96813d6863.js"></script><script defer="" src="/core/_next/static/kCEv-OaEfIzdZANpKRSyh/_buildManifest.js"></script><script defer="" src="/core/_next/static/kCEv-OaEfIzdZANpKRSyh/_ssgManifest.js"></script><style data-styled="" data-styled-version="5.3.1">.esSgGS{background-color:#ffffffff;color:#004d8eff;border:2px solid #4d90c8ff;padding:0.5rem 1rem;font-size:1rem;line-height:1.5rem;font-weight:400;position:absolute;left:-62.4375rem;top:auto;overflow:hidden;height:0.0625rem;z-index:-999;outline:none;font-family:Arial,sans-serif !important;}/*!sc*/
.esSgGS:focus,.esSgGS:active{left:0rem;top:0rem;height:auto;overflow:auto;z-index:9999;}/*!sc*/
@media (min-width:600px){.esSgGS{font-size:1.25rem;line-height:1.875rem;font-weight:400;padding:0.625rem 1.625rem;}.esSgGS:focus,.esSgGS:active{left:3.75rem;top:1.875rem;}}/*!sc*/
data-styled.g1[id="sc-bdfBQB"]{content:"esSgGS,"}/*!sc*/
.VwWUA{-webkit-appearance:none;-moz-appearance:none;appearance:none;position:relative;background:#b6bbc2ff;width:1.5rem;height:0.625rem;border-radius:0.4375rem;cursor:pointer;-webkit-transition:background 200ms ease,left 200ms ease;transition:background 200ms ease,left 200ms ease;will-change:background,left;}/*!sc*/
.VwWUA::after{position:absolute;content:'';width:0.875rem;height:0.875rem;background:#f2f3f4ff;box-shadow:0px 0px 1px rgba(0,0,0,0.12),0px 1px 1px rgba(0,0,0,0.25);border-radius:50%;left:-0.125rem;top:-0.125rem;-webkit-transition:background 200ms ease,left 200ms ease;transition:background 200ms ease,left 200ms ease;will-change:background,left;}/*!sc*/
.VwWUA:checked{background:#ffa973ff;}/*!sc*/
.VwWUA:checked::after{background:#ff6500ff;left:0.625rem;}/*!sc*/
.VwWUA:disabled{background:#f2f3f4ff;}/*!sc*/
.VwWUA:disabled::after{background:#f2f3f4ff;}/*!sc*/
data-styled.g5[id="sc-eCstlR"]{content:"VwWUA,"}/*!sc*/
.iZainC{position:relative;}/*!sc*/
data-styled.g6[id="sc-jSgvzq"]{content:"iZainC,"}/*!sc*/
.hsxhyr{position:relative;border-style:solid;border-width:0.0625rem;border-radius:0.25rem;border-color:#7f858dff;}/*!sc*/
.hsxhyr input,.hsxhyr textarea{width:100%;background:none;padding:0.6875rem 1rem;font-family:'"Poppins",sans-serif';color:#565c69ff;font-size:0.75rem;line-height:1rem;}/*!sc*/
@media (min-width:600px){.hsxhyr input,.hsxhyr textarea{font-size:0.875rem;line-height:1.5rem;}}/*!sc*/
.hsxhyr input::-webkit-input-placeholder,.hsxhyr textarea::-webkit-input-placeholder{color:transparent;}/*!sc*/
.hsxhyr input::-moz-placeholder,.hsxhyr textarea::-moz-placeholder{color:transparent;}/*!sc*/
.hsxhyr input:-ms-input-placeholder,.hsxhyr textarea:-ms-input-placeholder{color:transparent;}/*!sc*/
.hsxhyr input::placeholder,.hsxhyr textarea::placeholder{color:transparent;}/*!sc*/
.hsxhyr:focus-within{outline:none;border-color:#ff6500ff;}/*!sc*/
.hsxhyr input:focus,.hsxhyr textarea:focus{outline:none;border-color:#ff6500ff;}/*!sc*/
.hsxhyr input:focus::-webkit-input-placeholder,.hsxhyr textarea:focus::-webkit-input-placeholder{color:#7f858dff;}/*!sc*/
.hsxhyr input:focus::-moz-placeholder,.hsxhyr textarea:focus::-moz-placeholder{color:#7f858dff;}/*!sc*/
.hsxhyr input:focus:-ms-input-placeholder,.hsxhyr textarea:focus:-ms-input-placeholder{color:#7f858dff;}/*!sc*/
.hsxhyr input:focus::placeholder,.hsxhyr textarea:focus::placeholder{color:#7f858dff;}/*!sc*/
.hsxhyr input:focus ~ label,.hsxhyr textarea:focus ~ label{color:#ff6500ff;}/*!sc*/
.hsxhyr label{position:absolute;pointer-events:none;left:1rem;top:50%;-webkit-transform:translateY(-50%);-ms-transform:translateY(-50%);transform:translateY(-50%);-webkit-transition:300ms ease all;transition:300ms ease all;color:#565c69ff;font-size:0.75rem;line-height:1rem;}/*!sc*/
@media (min-width:600px){.hsxhyr label{font-size:0.875rem;line-height:1.5rem;}}/*!sc*/
.hsxhyr input:focus ~ label,.hsxhyr input:-webkit-autofill ~ label,.hsxhyr input:not([value='']) ~ label{top:0px;left:0.75rem;background-color:#fff;padding:0 0.125rem;font-size:0.75rem;line-height:1.125rem;}/*!sc*/
data-styled.g7[id="sc-gKseQn"]{content:"hsxhyr,"}/*!sc*/
.jXGcA{width:100%;display:grid;margin-left:auto;margin-right:auto;box-sizing:border-box;background-color:transparent;padding-left:1rem;padding-right:1rem;}/*!sc*/
@media (min-width:600px){.jXGcA{padding-left:1rem;padding-right:1rem;}}/*!sc*/
@media (min-width:1024px){.jXGcA{max-width:calc( 2rem + 76rem + 2rem );padding-left:2rem;padding-right:2rem;}}/*!sc*/
@media (min-width:1441px){.jXGcA{max-width:calc( 2rem + 94rem + 2rem );padding-left:2rem;padding-right:2rem;}}/*!sc*/
.MWOac{width:100%;display:grid;margin-left:auto;margin-right:auto;box-sizing:border-box;background-color:transparent;padding-left:0;padding-right:0;}/*!sc*/
@media (min-width:600px){.MWOac{padding-left:0;padding-right:0;}}/*!sc*/
@media (min-width:1024px){.MWOac{max-width:calc( 2rem + 76rem + 2rem );padding-left:2rem;padding-right:2rem;}}/*!sc*/
@media (min-width:1441px){.MWOac{max-width:calc( 2rem + 94rem + 2rem );padding-left:2rem;padding-right:2rem;}}/*!sc*/
data-styled.g101[id="sc-tYqdw"]{content:"jXGcA,MWOac,"}/*!sc*/
.byagXo{display:grid;width:100%;grid-template-columns:repeat(4,1fr);gap:0.5rem;}/*!sc*/
@media (min-width:600px){.byagXo{grid-template-columns:repeat(6,1fr);gap:1rem;}}/*!sc*/
@media (min-width:1024px){.byagXo{grid-template-columns:repeat(12,1fr);gap:2rem;}}/*!sc*/
data-styled.g102[id="sc-biBsmb"]{content:"byagXo,"}/*!sc*/
.cfeeGo{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 4;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;}/*!sc*/
@media (min-width:600px){.cfeeGo{-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 6;}}/*!sc*/
@media (min-width:1024px){.cfeeGo{-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 12;}}/*!sc*/
@media (min-width:1441px){.cfeeGo{-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 12;}}/*!sc*/
.dBdbHk{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 4;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;}/*!sc*/
@media (min-width:600px){.dBdbHk{-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 6;}}/*!sc*/
@media (min-width:1024px){.dBdbHk{-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 12;}}/*!sc*/
@media (min-width:1441px){.dBdbHk{-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 12;}}/*!sc*/
.kkcHbl{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 4;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;}/*!sc*/
@media (min-width:600px){.kkcHbl{-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 6;}}/*!sc*/
@media (min-width:1024px){.kkcHbl{-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 3;}}/*!sc*/
@media (min-width:1441px){.kkcHbl{-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 2;}}/*!sc*/
.cHpHOM{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 4;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;}/*!sc*/
@media (min-width:600px){.cHpHOM{-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;grid-column:span 6;}}/*!sc*/

In [5]:
script_tag = soup.find("script", id="__NEXT_DATA__")
script_tag

<script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"data":"{\"catalogServer\":{\"meta\":{\"breadcrumb\":[{\"id\":1,\"name\":\"Hardware\",\"path\":\"/hardware\"},{\"id\":11,\"name\":\"Memória RAM\",\"path\":\"/memoria-ram\"}],\"seo\":{\"title\":\"Memória RAM DDR5, DDR4 para PC e notebook\",\"description\":\"Memórias RAM 8GB, 16GB e 32GB com descontos imperdíveis. Acelere seu PC ou notebook com performance confiável\",\"titleHeading\":\"Memória RAM em promoção no KaBuM!\\r\"},\"promotion\":{\"title\":\"\",\"description\":\"\"},\"totalItemsCount\":1151,\"totalPagesCount\":20,\"page\":{\"cursor\":\"\",\"number\":1,\"size\":60,\"isCurrentPage\":true},\"filters\":[{\"name\":\"has_flash\",\"values\":[false],\"text\":\"Entrega Flash\"},{\"name\":\"has_offer\",\"values\":[false,true],\"text\":\"Oferta\"},{\"name\":\"has_open_box\",\"values\":[false,true],\"text\":\"Openbox\"},{\"name\":\"has_prime\",\"values\":[false],\"text\":\"Prime\"},{\"name\":\"kabum_product\",\"values\":[false,true],\"text\":\"KaBuM!\"},{\"name\":\"category\",\"values\":[\"Hardware\"],\"text\":\"Categorias\"},{\"name\":\"manufacturer\",\"values\":[\"Adata\",\"Arktek\",\"ASUS\",\"Asustor\",\"Best Baterry\",\"BEST BATTERY\",\"BEST MEMORY\",\"Bluecase\",\"Brazil PC\",\"BRAZILPC\",\"Ceamere\",\"Chroma Tech\",\"Corsair\",\"Crucial\",\"Dahua\",\"Dell\",\"Duex\",\"Easy Memory\",\"Fnx\",\"Generico\",\"GOLDEN MEMORY\",\"GOLDENTEC ACESSORIOS\",\"G.skill\",\"HAYLOU\",\"Hayom\",\"Hiksemi\",\"Hp\",\"Husky\",\"HYNIX\",\"Hyperx\",\"Hyper X\",\"Ibm\",\"Intel\",\"KEEPDATA\",\"KING\",\"KingFast\",\"Kingspec\",\"Kingston\",\"Kingston FURY\",\"Klevv\",\"Knup\",\"Ktrok\",\"Lenovo\",\"Lexar\",\"MACROVIP\",\"Macroway\",\"Markvision\",\"Memory one\",\"Micron\",\"Multi\",\"MUSHKIN\",\"Nanya\",\"Netac\",\"Netcore\",\"NTC\",\"OEM\",\"Outros\",\"Oxy\",\"OxyBr\",\"Patriot\",\"PCYES\",\"Qnap\",\"Redragon\",\"Rise Mode\",\"Samsung\",\"SK HYNIX\",\"Smart\",\"SMART PC\",\"Team Group\",\"TOB COMPUTERS\",\"Up Gamer\",\"Xlinne\",\"X-Linne\",\"XPG\"],\"text\":\"Marcas\"},{\"name\":\"Compatibilidade\",\"values\":[\"Computadores (PC)\",\"Notebook\",\"Servidores\"],\"text\":\"Compatibilidade\"},{\"name\":\"Iluminação RGB\",\"values\":[\"Não\",\"Sim\"],\"text\":\"Iluminação RGB\"},{\"name\":\"Capacidade\",\"values\":[\"128 GB (1x 128GB)\",\"128 GB (2x 64GB)\",\"128 GB (4x 32GB)\",\"16 GB (1x 16GB)\",\"16 GB (2x 8GB)\",\"1 GB (1x 1GB)\",\"24 GB (1x 24GB)\",\"256 GB (1x 256GB)\",\"256 GB (8x 32GB)\",\"2 GB (1x 2GB)\",\"32 GB (1x 32GB)\",\"32 GB (2x 16GB)\",\"32 GB (4x 8GB)\",\"48 GB (1x 48GB)\",\"4 GB (1x 4GB)\",\"64 GB (1x 64GB)\",\"64 GB (2x 32GB)\",\"64 GB (4x 16GB)\",\"8 GB (1x 8GB)\",\"8 GB (2x 4GB)\",\"96 GB (2x 48GB)\"],\"text\":\"Capacidade\"},{\"name\":\"Velocidade\",\"values\":[\"1066 MHz\",\"1333 MHz\",\"1600 MHz\",\"1866 MHz\",\"2133 MHz\",\"2400 MHz\",\"2666 MHz\",\"266 MHz\",\"2933 MHz\",\"3200 MHz\",\"3600 MHz\",\"3733 MHz\",\"4000 MHz\",\"4600 MHz\",\"4800 MHz\",\"5200 MHz\",\"533 MHz\",\"5600 MHz\",\"6000 MHz\",\"6200 MHz\",\"6400 MHz\",\"6600 MHz\",\"667 MHz\",\"7000 MHz\",\"7600 MHz\",\"800 MHz\"],\"text\":\"Velocidade\"},{\"name\":\"Armazenamento\",\"values\":[\"16 GB\"],\"text\":\"Armazenamento\"},{\"name\":\"Portátil\",\"values\":[\"Não\"],\"text\":\"Portátil\"},{\"name\":\"price\",\"min\":24.99,\"max\":18991.75,\"text\":\"Preço\"},{\"name\":\"highlighted_free_shipping\",\"values\":[false,true],\"text\":\"Frete Grátis\"}]},\"links\":{\"redirect\":\"/hardware/memoria-ram\",\"first\":\"/catalog/v2/products-by-category/hardware/memoria-ram?sort=most_searched\u0026page_cursor=Tk9UIElTIFVTRQ==\u0026page_number=1\u0026page_size=60\",\"self\":\"/catalog/v2/products-by-category/hardware/memoria-ram?sort=most_searched\u0026page_cursor=\u0026page_number=1\u0026page_size=60\",\"last\":\"/catalog/v2/products-by-category/hardware/memoria-ram?sort=most_searched\u0026page_cursor=Tk9UIElTIFVTRQ==\u0026page_number=20\u0026page_size=60\",\"next\":\"/catalog/v2/products-by-category/hardware/memoria-ram?sort=most_searched\u0026page_cursor=Tk9UIElTIFVTRQ==\u0026page_number=2\u0026page_size=60\"},\"data\":[{\"code\":922165,\"productSpecie\":0,\"name\":\"Memória RAM Husky Impulse, 8GB, 3200MHz, DDR4, CL22, Preto - HRM001083222PT\",\"description\":\"\u003ch2\u003eMem\u0026oacute;ria RAM Husky Impulse DDR4: Desempenho de Elite para o seu PC Gamer\u003c/h2\u003e\\n\u003cp\u003eA \u003cstrong\u003eMem\u0026oacute;ria RAM Husky Impulse\u003c/strong\u003e \u0026eacute; o \u003cstrong\u003eupgrade\u003c/strong\u003e ideal para gamers que buscam a m\u0026aacute;xima performance. Focada em velocidade e efici\u0026ecirc;ncia, ela eleva a experi\u0026ecirc;ncia de jogo a um novo patamar, garantindo que voc\u0026ecirc; rode seus t\u0026iacute;tulos favoritos com total fluidez, sem travamentos ou lentid\u0026atilde;o.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eVelocidade Extrema com 3200MHz\u003c/h3\u003e\\n\u003cp\u003ePrepare-se para uma jogabilidade mais suave e carregamentos mais r\u0026aacute;pidos. Com sua frequ\u0026ecirc;ncia de \u003cstrong\u003e3200MHz\u003c/strong\u003e, a \u003cstrong\u003eHusky Impulse oferece\u003c/strong\u003e um desempenho equilibrado e de alta velocidade. Essa caracter\u0026iacute;stica \u0026eacute; fundamental para jogos e aplicativos exigentes, permitindo que seu PC processe dados de forma ultrarr\u0026aacute;pida.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eTecnologia DDR4 e Capacidade de 8gb\u003c/h3\u003e\\n\u003cp\u003eA\u003cstrong\u003e Husky Impulse\u003c/strong\u003e utiliza a avan\u0026ccedil;ada\u003cstrong\u003e tecnologia DDR4,\u003c/strong\u003e uma evolu\u0026ccedil;\u0026atilde;o que proporciona maior largura de banda e melhor efici\u0026ecirc;ncia energ\u0026eacute;tica comparada com a gera\u0026ccedil;\u0026atilde;o anterior. Al\u0026eacute;m disso, com \u003cstrong\u003e8GB\u003c/strong\u003e de capacidade, voc\u0026ecirc; pode rodar \u003cstrong\u003em\u0026uacute;ltiplos programas\u003c/strong\u003e e\u003cstrong\u003e jogos pesados \u003c/strong\u003esimultaneamente, como transmiss\u0026otilde;es ao vivo e edi\u0026ccedil;\u0026atilde;o de v\u0026iacute;deos, sem comprometer a performance do seu sistema.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eLat\u0026ecirc;ncia CL22 Otimizada para Jogos\u003c/h3\u003e\\n\u003cp\u003eEmbora a lat\u0026ecirc;ncia \u003cstrong\u003eCL22\u003c/strong\u003e equilibre o custo-benef\u0026iacute;cio, ela \u0026eacute; perfeitamente otimizada para garantir um bom desempenho em \u003cstrong\u003ejogos\u003c/strong\u003e e aplicativos. Essa \u003cstrong\u003elat\u0026ecirc;ncia\u003c/strong\u003e contribui para o tempo de resposta \u0026aacute;gil, garantindo que suas a\u0026ccedil;\u0026otilde;es no jogo sejam registradas sem atrasos percept\u0026iacute;veis, o que \u0026eacute; crucial em partidas online e t\u0026iacute;tulos competitivos.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eAdquira o seu no KaBuM!\u003c/h3\u003e\",\"tagDescription\":\"A Memória RAM Husky Impulse, É só no KaBuM!!! Garanta já o seu. Tudo isso você encontra no KaBuM!\",\"weight\":66,\"friendlyName\":\"memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt\",\"sellerName\":\"KaBuM!\",\"sellerId\":0,\"offerIdMarketplace\":0,\"category\":\"Hardware/Memória RAM/DDR 4/3200MHz\",\"externalUrl\":\"\",\"manufacturer\":{\"id\":2317,\"name\":\"Husky\",\"img\":\"https://images4.kabum.com.br/produtos/fabricantes/logo-husky.jpg\"},\"iframeUrl\":\"\",\"image\":\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_original.jpg\",\"images\":[\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_original.jpg\"],\"price\":858.81,\"primePrice\":0,\"primePriceWithDiscount\":0,\"discountPercentagePrime\":0,\"oldPrice\":0,\"oldPrimePrice\":0,\"maxInstallment\":\"10x de R$ 85,88\",\"priceWithDiscount\":729.99,\"priceMarketplace\":0,\"discountPercentage\":15,\"offerDiscount\":0,\"quantity\":0,\"rating\":5,\"ratingCount\":180,\"available\":true,\"preOrderDate\":0,\"warranty\":\"3 anos de garantia (3 meses de garantia legal + 33 meses de garantia contratual junto ao fabricante)\",\"dateProductArrived\":null,\"html\":null,\"ufsFlash\":[],\"stamps\":null,\"flags\":{\"isMarketplace\":false,\"isOpenbox\":false,\"isFreeShipping\":false,\"isFreeShippingPrime\":false,\"isPixShipping\":false,\"isPreOrder\":false,\"isFlash\":false,\"isPrime\":false,\"isOffer\":false,\"hasGift\":false,\"isHighlight\":false},\"origin\":{\"id\":null,\"name\":null},\"prime\":null,\"offer\":null,\"colors\":{\"main\":\"\",\"text\":\"#fff\"},\"paymentMethodsDefault\":null,\"paymentMethodsPrime\":null,\"tagCode\":0,\"photos\":{\"p\":[\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_p.jpg\"],\"m\":[\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_m.jpg\"],\"g\":[\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_g.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_g.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_g.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_g.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_g.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_g.jpg\"],\"gg\":[\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_gg.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_gg.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_gg.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_gg.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_gg.jpg\",\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_gg.jpg\"]},\"thumbnail\":\"https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_m.jpg\",\"promotionBanner\":null,\"campaignBanners\":null,\"crossCart\":[],\"crossSelling\":false,\"ageRating\":0},{\"code\":172365,\"productSpecie\":0,\"name\":\"Memória RAM Kingston Fury Beast, 8GB, 3200MHz, DDR4, CL16, Preto - KF432C16BB/8\",\"description\":\"\u003ch2\u003eMem\u0026oacute;ria Kingston FURY Beast DDR4\u003c/h2\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eDesempenho M\u0026aacute;ximo para Suas Aventuras Digitais!\u003c/h3\u003e\\n\u003cp\u003eLiberte o potencial m\u0026aacute;ximo do seu computador com a Mem\u0026oacute;ria Kingston FURY Beast DDR4! Projetada para gamers, editores de v\u0026iacute;deo e profissionais de renderiza\u0026ccedil;\u0026atilde;o, esta mem\u0026oacute;ria oferece um \u003cstrong\u003eaumento de performance\u003c/strong\u003e poderoso e confi\u0026aacute;vel.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eOverclock Autom\u0026aacute;tico Plug N Play\u003c/h3\u003e\\n\u003cp\u003eA FURY Beast \u003cstrong\u003eDDR4\u003c/strong\u003e ajusta-se automaticamente \u0026agrave; velocidade m\u0026aacute;xima suportada pelo seu sistema, sem necessidade de configura\u0026ccedil;\u0026otilde;es complexas.\u003c/p\u003e\\n\u003cp\u003e\u003cstrong\u003eCompatibilidade\u003c/strong\u003e Total: Pronta para \u003cstrong\u003eIntel XMP e AMD Ryzen\u003c/strong\u003e, garantindo integra\u0026ccedil;\u0026atilde;o perfeita com as plataformas mais populares.\u003c/p\u003e\\n\u003cp\u003e\u003cstrong\u003eVelocidades Incr\u0026iacute;veis\u003c/strong\u003e: Experimente tempos de \u003cstrong\u003ecarregamento ultrarr\u0026aacute;pidos\u003c/strong\u003e e multitarefa suave para jogos, edi\u0026ccedil;\u0026atilde;o de v\u0026iacute;deo e muito mais.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eRefrigera\u0026ccedil;\u0026atilde;o e Confiabilidade\u003c/h3\u003e\\n\u003cp\u003e\u003cstrong\u003eDissipador de Calor\u003c/strong\u003e de Perfil Baixo: Mantenha sua mem\u0026oacute;ria fria e funcionando com desempenho m\u0026aacute;ximo, mesmo durante as sess\u0026otilde;es de uso mais intensas.\u003c/p\u003e\\n\u003cp\u003eQualidade Kingston: 100% testada na f\u0026aacute;brica para garantir a m\u0026aacute;xima confiabilidade e durabilidade.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eImportante - Verifique a compatibilidade do seu sistema:\u003c/h3\u003e\\n\u003cp\u003eProcessadores Intel de 7\u0026ordf; gera\u0026ccedil;\u0026atilde;o e chipsets da s\u0026eacute;rie 200 podem exigir uma atualiza\u0026ccedil;\u0026atilde;o da BIOS para suportar m\u0026oacute;dulos de mem\u0026oacute;ria DDR4 com chips DRAM de densidade 16Gbit. Processadores de 6\u0026ordf; gera\u0026ccedil;\u0026atilde;o e chipsets da s\u0026eacute;rie 100 n\u0026atilde;o s\u0026atilde;o compat\u0026iacute;veis.\u003c/p\u003e\\n\u003cp\u003e\u0026nbsp;\u003c/p\u003e\\n\u003ch3\u003eCompre agora no KaBuM!\u003c/h3\u003e\",\"tagDescription\":\"Compre Memória Kingston Fury Beast no KaBuM! As melhores ofertas com ótimas condições de pagamento. Descubra a melhor forma de comprar online!\",\"weight\":50,\"friendlyName\":\"memoria-ram-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8\",\"sellerName\":\"KaBuM!\",\"sellerId\":0,\"offerIdMarketplace\":0,\"category\":\"Hardware/Memória RAM/DDR 4\",\"externalUrl\":\"\",\"manufacturer\":{\"id\":50,\"name\":\"Kingston\",\"img\":\"https://images4.kabum.com.br/produtos/fabricantes/logo-kingston.jpg\"},\"iframeUrl\":\"\",\"image\":\"https://images.kabum.com.br/produtos/fotos/172365/memoria-ram-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1742845663_original.jpg\",\"images\":[\"https://images.kabum.com.br/produtos/fotos/172365/memoria-ram-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1742845663_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270526_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270525_original.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270524_original.jpg\"],\"price\":823.52,\"primePrice\":0,\"primePriceWithDiscount\":0,\"discountPercentagePrime\":0,\"oldPrice\":823.52,\"oldPrimePrice\":823.52,\"maxInstallment\":\"10x de R$ 59,88\",\"priceWithDiscount\":699.99,\"priceMarketplace\":0,\"discountPercentage\":15,\"offerDiscount\":0,\"quantity\":920,\"rating\":5,\"ratingCount\":1478,\"available\":true,\"preOrderDate\":0,\"warranty\":\"10 anos de garantia (3 meses de garantia legal + 117 meses de garantia contratual junto ao fabricante)\",\"dateProductArrived\":null,\"html\":null,\"ufsFlash\":[],\"stamps\":null,\"flags\":{\"isMarketplace\":false,\"isOpenbox\":false,\"isFreeShipping\":false,\"isFreeShippingPrime\":false,\"isPixShipping\":false,\"isPreOrder\":false,\"isFlash\":false,\"isPrime\":false,\"isOffer\":true,\"hasGift\":false,\"isHighlight\":false},\"origin\":{\"id\":null,\"name\":null},\"prime\":null,\"offer\":{\"id\":\"977566\",\"name\":\"PAY DAY\",\"referenceBanner\":\"payday\",\"endsAt\":1775739600,\"startsAt\":1775571060,\"isPrimeExclusive\":null,\"price\":598.81,\"priceWithDiscount\":508.99,\"discountPercentage\":27,\"quantityAvailable\":920,\"hashCode\":\"dd66a3f6562d0b1d49e7421e1198aad984141478\"},\"colors\":{\"main\":\"\",\"text\":\"#fff\"},\"paymentMethodsDefault\":null,\"paymentMethodsPrime\":null,\"tagCode\":0,\"photos\":{\"p\":[\"https://images.kabum.com.br/produtos/fotos/172365/memoria-ram-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1742845663_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270526_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270525_p.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270524_p.jpg\"],\"m\":[\"https://images.kabum.com.br/produtos/fotos/172365/memoria-ram-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1742845663_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270526_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270525_m.jpg\",\"https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270524_m.jpg\"],\"g\":[\"https://images.kabum.com.br/produtos/fotos/172365/memoria-ram-kingston-fury-beas

## Coleta de dados

In [7]:
next_data = json.loads(script_tag.string)
catalog = json.loads(next_data["props"]["pageProps"]["data"])

print(json.dumps(catalog["catalogServer"]["data"][0], indent=2, ensure_ascii=False))

{
  "code": 922165,
  "productSpecie": 0,
  "name": "Memória RAM Husky Impulse, 8GB, 3200MHz, DDR4, CL22, Preto - HRM001083222PT",
  "description": "<h2>Mem&oacute;ria RAM Husky Impulse DDR4: Desempenho de Elite para o seu PC Gamer</h2>\n<p>A <strong>Mem&oacute;ria RAM Husky Impulse</strong> &eacute; o <strong>upgrade</strong> ideal para gamers que buscam a m&aacute;xima performance. Focada em velocidade e efici&ecirc;ncia, ela eleva a experi&ecirc;ncia de jogo a um novo patamar, garantindo que voc&ecirc; rode seus t&iacute;tulos favoritos com total fluidez, sem travamentos ou lentid&atilde;o.</p>\n<p>&nbsp;</p>\n<h3>Velocidade Extrema com 3200MHz</h3>\n<p>Prepare-se para uma jogabilidade mais suave e carregamentos mais r&aacute;pidos. Com sua frequ&ecirc;ncia de <strong>3200MHz</strong>, a <strong>Husky Impulse oferece</strong> um desempenho equilibrado e de alta velocidade. Essa caracter&iacute;stica &eacute; fundamental para jogos e aplicativos exigentes, permitindo que seu PC processe dados de forma ultrarr&aacute;pida.</p>\n<p>&nbsp;</p>\n<h3>Tecnologia DDR4 e Capacidade de 8gb</h3>\n<p>A<strong> Husky Impulse</strong> utiliza a avan&ccedil;ada<strong> tecnologia DDR4,</strong> uma evolu&ccedil;&atilde;o que proporciona maior largura de banda e melhor efici&ecirc;ncia energ&eacute;tica comparada com a gera&ccedil;&atilde;o anterior. Al&eacute;m disso, com <strong>8GB</strong> de capacidade, voc&ecirc; pode rodar <strong>m&uacute;ltiplos programas</strong> e<strong> jogos pesados </strong>simultaneamente, como transmiss&otilde;es ao vivo e edi&ccedil;&atilde;o de v&iacute;deos, sem comprometer a performance do seu sistema.</p>\n<p>&nbsp;</p>\n<h3>Lat&ecirc;ncia CL22 Otimizada para Jogos</h3>\n<p>Embora a lat&ecirc;ncia <strong>CL22</strong> equilibre o custo-benef&iacute;cio, ela &eacute; perfeitamente otimizada para garantir um bom desempenho em <strong>jogos</strong> e aplicativos. Essa <strong>lat&ecirc;ncia</strong> contribui para o tempo de resposta &aacute;gil, garantindo que suas a&ccedil;&otilde;es no jogo sejam registradas sem atrasos percept&iacute;veis, o que &eacute; crucial em partidas online e t&iacute;tulos competitivos.</p>\n<p>&nbsp;</p>\n<h3>Adquira o seu no KaBuM!</h3>",
  "tagDescription": "A Memória RAM Husky Impulse, É só no KaBuM!!! Garanta já o seu. Tudo isso você encontra no KaBuM!",
  "weight": 66,
  "friendlyName": "memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt",
  "sellerName": "KaBuM!",
  "sellerId": 0,
  "offerIdMarketplace": 0,
  "category": "Hardware/Memória RAM/DDR 4/3200MHz",
  "externalUrl": "",
  "manufacturer": {
    "id": 2317,
    "name": "Husky",
    "img": "https://images4.kabum.com.br/produtos/fabricantes/logo-husky.jpg"
  },
  "iframeUrl": "",
  "image": "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_original.jpg",
  "images": [
    "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_original.jpg",
    "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_original.jpg",
    "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_original.jpg",
    "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_original.jpg",
    "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_original.jpg",
    "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_original.jpg"
  ],
  "price": 858.81,
  "primePrice": 0,
  "primePriceWithDiscount": 0,
  "discountPercentagePrime": 0,
  "oldPrice": 0,
  "oldPrimePrice": 0,
  "maxInstallment": "10x de R$ 85,88",
  "priceWithDiscount": 729.99,
  "priceMarketplace": 0,
  "discountPercentage": 15,
  "offerDiscount": 0,
  "quantity": 0,
  "rating": 5,
  "ratingCount": 180,
  "available": true,
  "preOrderDate": 0,
  "warranty": "3 anos de garantia (3 meses de garantia legal + 33 meses de garantia contratual junto ao fabricante)",
  "dateProductArrived": null,
  "html": null,
  "ufsFlash": [],
  "stamps": null,
  "flags": {
    "isMarketplace": false,
    "isOpenbox": false,
    "isFreeShipping": false,
    "isFreeShippingPrime": false,
    "isPixShipping": false,
    "isPreOrder": false,
    "isFlash": false,
    "isPrime": false,
    "isOffer": false,
    "hasGift": false,
    "isHighlight": false
  },
  "origin": {
    "id": null,
    "name": null
  },
  "prime": null,
  "offer": null,
  "colors": {
    "main": "",
    "text": "#fff"
  },
  "paymentMethodsDefault": null,
  "paymentMethodsPrime": null,
  "tagCode": 0,
  "photos": {
    "p": [
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_p.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_p.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_p.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_p.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_p.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_p.jpg"
    ],
    "m": [
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_m.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_m.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_m.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_m.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_m.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_m.jpg"
    ],
    "g": [
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_g.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_g.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_g.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_g.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_g.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_g.jpg"
    ],
    "gg": [
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_gg.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_gg.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_gg.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_gg.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_gg.jpg",
      "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_gg.jpg"
    ]
  },
  "thumbnail": "https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_m.jpg",
  "promotionBanner": null,
  "campaignBanners": null,
  "crossCart": [],
  "crossSelling": false,
  "ageRating": 0
}

localiza a tag __NEXT_DATA__ que o Next.js injeta no HTML, e faz dois json.loads porque pageProps["data"] é uma string JSON dentro do JSON principal.

In [16]:
# __NEXT_DATA__ — pageProps.data é uma string JSON, precisa parsear duas vezes
script_next = soup.find("script", id="__NEXT_DATA__")
next_data = json.loads(script_next.string)

# pageProps["data"] é uma string — precisa de um segundo json.loads
catalog = json.loads(next_data["props"]["pageProps"]["data"])

# print("Chaves do catalog:")
# print(list(catalog.keys()))

produtos_raw = catalog["catalogServer"]["data"]
print(f"\nProdutos encontrados: {len(produtos_raw)}")
# print("\nPrimeiro produto:")
print(produtos_raw[0])

Produtos encontrados: 60
{'code': 922165, 'productSpecie': 0, 'name': 'Memória RAM Husky Impulse, 8GB, 3200MHz, DDR4, CL22, Preto - HRM001083222PT', 'description': '<h2>Mem&oacute;ria RAM Husky Impulse DDR4: Desempenho de Elite para o seu PC Gamer</h2>\n<p>A <strong>Mem&oacute;ria RAM Husky Impulse</strong> &eacute; o <strong>upgrade</strong> ideal para gamers que buscam a m&aacute;xima performance. Focada em velocidade e efici&ecirc;ncia, ela eleva a experi&ecirc;ncia de jogo a um novo patamar, garantindo que voc&ecirc; rode seus t&iacute;tulos favoritos com total fluidez, sem travamentos ou lentid&atilde;o.</p>\n<p>&nbsp;</p>\n<h3>Velocidade Extrema com 3200MHz</h3>\n<p>Prepare-se para uma jogabilidade mais suave e carregamentos mais r&aacute;pidos. Com sua frequ&ecirc;ncia de <strong>3200MHz</strong>, a <strong>Husky Impulse oferece</strong> um desempenho equilibrado e de alta velocidade. Essa caracter&iacute;stica &eacute; fundamental para jogos e aplicativos exigentes, permitindo que seu PC processe dados de forma ultrarr&aacute;pida.</p>\n<p>&nbsp;</p>\n<h3>Tecnologia DDR4 e Capacidade de 8gb</h3>\n<p>A<strong> Husky Impulse</strong> utiliza a avan&ccedil;ada<strong> tecnologia DDR4,</strong> uma evolu&ccedil;&atilde;o que proporciona maior largura de banda e melhor efici&ecirc;ncia energ&eacute;tica comparada com a gera&ccedil;&atilde;o anterior. Al&eacute;m disso, com <strong>8GB</strong> de capacidade, voc&ecirc; pode rodar <strong>m&uacute;ltiplos programas</strong> e<strong> jogos pesados </strong>simultaneamente, como transmiss&otilde;es ao vivo e edi&ccedil;&atilde;o de v&iacute;deos, sem comprometer a performance do seu sistema.</p>\n<p>&nbsp;</p>\n<h3>Lat&ecirc;ncia CL22 Otimizada para Jogos</h3>\n<p>Embora a lat&ecirc;ncia <strong>CL22</strong> equilibre o custo-benef&iacute;cio, ela &eacute; perfeitamente otimizada para garantir um bom desempenho em <strong>jogos</strong> e aplicativos. Essa <strong>lat&ecirc;ncia</strong> contribui para o tempo de resposta &aacute;gil, garantindo que suas a&ccedil;&otilde;es no jogo sejam registradas sem atrasos percept&iacute;veis, o que &eacute; crucial em partidas online e t&iacute;tulos competitivos.</p>\n<p>&nbsp;</p>\n<h3>Adquira o seu no KaBuM!</h3>', 'tagDescription': 'A Memória RAM Husky Impulse, É só no KaBuM!!! Garanta já o seu. Tudo isso você encontra no KaBuM!', 'weight': 66, 'friendlyName': 'memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt', 'sellerName': 'KaBuM!', 'sellerId': 0, 'offerIdMarketplace': 0, 'category': 'Hardware/Memória RAM/DDR 4/3200MHz', 'externalUrl': '', 'manufacturer': {'id': 2317, 'name': 'Husky', 'img': 'https://images4.kabum.com.br/produtos/fabricantes/logo-husky.jpg'}, 'iframeUrl': '', 'image': 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_original.jpg', 'images': ['https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_original.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_original.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_original.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_original.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_original.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_original.jpg'], 'price': 858.81, 'primePrice': 0, 'primePriceWithDiscount': 0, 'discountPercentagePrime': 0, 'oldPrice': 0, 'oldPrimePrice': 0, 'maxInstallment': '10x de R$ 85,88', 'priceWithDiscount': 729.99, 'priceMarketplace': 0, 'discountPercentage': 15, 'offerDiscount': 0, 'quantity': 0, 'rating': 5, 'ratingCount': 180, 'available': True, 'preOrderDate': 0, 'warranty': '3 anos de garantia (3 meses de garantia legal + 33 meses de garantia contratual junto ao fabricante)', 'dateProductArrived': None, 'html': None, 'ufsFlash': [], 'stamps': None, 'flags': {'isMarketplace': False, 'isOpenbox': False, 'isFreeShipping': False, 'isFreeShippingPrime': False, 'isPixShipping': False, 'isPreOrder': False, 'isFlash': False, 'isPrime': False, 'isOffer': False, 'hasGift': False, 'isHighlight': False}, 'origin': {'id': None, 'name': None}, 'prime': None, 'offer': None, 'colors': {'main': '', 'text': '#fff'}, 'paymentMethodsDefault': None, 'paymentMethodsPrime': None, 'tagCode': 0, 'photos': {'p': ['https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_p.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_p.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_p.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_p.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_p.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_p.jpg'], 'm': ['https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_m.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_m.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_m.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_m.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_m.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_m.jpg'], 'g': ['https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_g.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_g.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_g.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_g.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_g.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_g.jpg'], 'gg': ['https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_gg.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013533_gg.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013534_gg.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013536_gg.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013537_gg.jpg', 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013538_gg.jpg']}, 'thumbnail': 'https://images.kabum.com.br/produtos/fotos/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt_1764013535_m.jpg', 'promotionBanner': None, 'campaignBanners': None, 'crossCart': [], 'crossSelling': False, 'ageRating': 0}

In [17]:
def extrair_produto(produto):
    return {
        "id":             produto.get("code"),
        "nome":           produto.get("name"),
        "preco_original": produto.get("oldPrice"),
        "preco_atual":    produto.get("price"),
        "preco_pix":      produto.get("priceWithDiscount"),
        "desconto_pct":   produto.get("discountPercentage"),
        "avaliacao":      produto.get("rating"),
        "num_avaliacoes": produto.get("ratingCount"),
        "disponivel":     produto.get("available"),
        "fabricante":     produto.get("manufacturer", {}).get("name"),
        "categoria":      produto.get("category"),
        "garantia":       produto.get("warranty"),
        "frete_gratis":   produto.get("flags", {}).get("isFreeShipping"),
        "url": f"https://www.kabum.com.br/produto/{produto.get('code')}/{produto.get('friendlyName', '')}",
    }

produtos_bs4 = [extrair_produto(p) for p in produtos_raw]
print(f"Produtos extraídos: {len(produtos_bs4)}")
produtos_bs4[0]

Produtos extraídos: 60

{'id': 922165,
 'nome': 'Memória RAM Husky Impulse, 8GB, 3200MHz, DDR4, CL22, Preto - HRM001083222PT',
 'preco_original': 0,
 'preco_atual': 858.81,
 'preco_pix': 729.99,
 'desconto_pct': 15,
 'avaliacao': 5,
 'num_avaliacoes': 180,
 'disponivel': True,
 'fabricante': 'Husky',
 'categoria': 'Hardware/Memória RAM/DDR 4/3200MHz',
 'garantia': '3 anos de garantia (3 meses de garantia legal + 33 meses de garantia contratual junto ao fabricante)',
 'frete_gratis': False,
 'url': 'https://www.kabum.com.br/produto/922165/memoria-ram-husky-impulse-8gb-3200mhz-ddr4-cl22-preto-hrm001083222pt'}

## Todas as páginas

In [19]:
todos_produtos = []

NUM_PAGINAS = 20  

for pagina in range(1, NUM_PAGINAS + 1):
    url = f"https://www.kabum.com.br/hardware/memoria-ram?page_number={pagina}"
    response = requests.get(url, headers=headers)
    print(f"Página {pagina}: {response.status_code}")

    soup = BeautifulSoup(response.text, "html.parser")
    script_next = soup.find("script", id="__NEXT_DATA__")
    catalog = json.loads(json.loads(script_next.string)["props"]["pageProps"]["data"])
    produtos_raw = catalog["catalogServer"]["data"]

    todos_produtos.extend([extrair_produto(p) for p in produtos_raw])
    time.sleep(random.uniform(0.5, 1.5))

print(f"\nTotal coletado: {len(todos_produtos)}")

Página 1: 200
Página 2: 200
Página 3: 200
Página 4: 200
Página 5: 200
Página 6: 200
Página 7: 200
Página 8: 200
Página 9: 200
Página 10: 200
Página 11: 200
Página 12: 200
Página 13: 200
Página 14: 200
Página 15: 200
Página 16: 200
Página 17: 200
Página 18: 200
Página 19: 200
Página 20: 200

Total coletado: 1151

## Salvando os dados

In [21]:
df = pd.DataFrame(todos_produtos)
# df.head()
# df.columns
df.shape

(1151, 14)

In [22]:
data_dir = pathlib.Path("data")
data_dir.mkdir(exist_ok=True)

# JSON
with (data_dir / "kabum_memoria_ram.json").open("w", encoding="utf-8") as f:
    json.dump(todos_produtos, f, ensure_ascii=False, indent=4)

# CSV
df = pd.DataFrame(todos_produtos)
df.to_csv(data_dir / "kabum_memoria_ram.csv", index=False, encoding="utf-8")

## Análises Futuras

Top 10 memórias mais baratas

In [ ]:
df.nsmallest(10, "preco_atual")[["nome", "preco_atual", "preco_pix", "desconto_pct"]]

,nome,preco_atual,preco_pix,desconto_pct
613,Memória P/ Notebook Ddr3 Pc3-10600 2gb,24.99,23.74,5
828,Memoria 1gb Ddr2 800mhz Sodimm,29.90,29.90,0
692,Memoria 2gb Ddr3 1333 Cl9 1.5v Desktop Sp312n...,54.90,51.06,7
1109,Memoria Kingston PC 1gb Ddr 400,55.77,55.77,0
445,"Memória Notebook Nanya, 2GB, 1333MHz, DDR3 - P...",60.01,60.01,0
582,"Memória Oxy, 4GB, 1600MHz, DDR3L, 1.35V, Para ...",62.63,62.63,0
557,"Memória Dale7, 2GB, 1333Mhz, DDR3, Desktop, 1.5v",63.89,63.89,0
863,"Memória Dale7, 2GB, 1600Mhz, DDR3, Desktop, 1.5v",63.89,63.89,0
606,"Memória Dale7, 2GB, 1333Mhz, DDR3, Notebook, 1.5v",67.89,67.89,0
740,"Memória Dale7, 2GB, 1600Mhz, DDR3, Notebook, 1.5v",67.89,67.89,0

Top 10 maiores descontos

In [25]:
df.nlargest(10, "desconto_pct")[["nome", "preco_original", "preco_atual", "desconto_pct"]]

,nome,preco_original,preco_atual,desconto_pct
192,"Memória Kingston DIMM, 8GB, 1600MHz, DDR3, 1.3...",0.0,824.0,22
218,"Memória Kingston HyperX Fury, 8GB, 3200MHz, DD...",0.0,849.3,22
292,"Memória Kingston SODIMM, 8GB, 2666MHz, DDR4, 1...",0.0,766.9,22
373,"Memória Kingston, 8GB, 1600MHz, DDR3, CL11, Pa...",0.0,758.0,22
513,"Memória Kingston, 4GB, 1600MHz, DDR3, CL11, Pa...",0.0,488.3,22
578,"Memória Kingston, 8GB, 2666MHz, DDR4, 1.2V, Pa...",0.0,744.3,22
1143,"Memória Kingston, 8GB, 1600MHz, DDR3, Para Not...",0.0,956.3,22
1144,"Memória Kingston, 4GB, 1600MHz, DDR3, Para Des...",0.0,544.3,22
1147,"Memória Kingston, 4GB, 1333MHz, DDR3, CL9",0.0,599.0,22
135,"Memória Gamer Xpg Spectrix D35g 16GB, RGB, DDR...",0.0,1305.0,20